version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/app
    restart: always
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/app
    restart: always
  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    volumes:
      - .:/var/www/app
    restart: always
    depends_on:
      - db
