default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:

development:
  <<: *default
  database: mintegimoves_development

test:
  <<: *default
  database: mintegimoves_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
