default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:

development:
  <<: *default
  database: mintegimoves_development

test:
  <<: *default
  database: mintegimoves_test

production:
  <<: *default
  host: db
  database: mintegimoves
  password: root
